### ISSUE TITLE
数据集方便分享吗

### ISSUE THREAD

**Issue by Calsia** [JunyaoHu/PaddlePaddleDemo#1]
如题,大佬数据集我想学习下,你方便分享吗

**Comment by JunyaoHu** [comment]
你好👋，这个数据集来自 https://aistudio.baidu.com/datasetdetail/91732

Original:
From:Calsia< ***@***.***>Date:2023-12-26 21:41:46To:JunyaoHu/PaddlePaddleDemo< ***@***.***>Cc:Subscribed< ***@***.***>Subject:[JunyaoHu/PaddlePaddleDemo] 数据集方便分享吗 (Issue #1)
如题,大佬数据集我想学习下,你方便分享吗

**Comment by Calsia** [comment]
> 你好👋，这个数据集来自 https://aistudio.baidu.com/datasetdetail/91732 Original: From:Calsia< ***@***.***>Date:2023-12-26 21:41:46To:JunyaoHu/PaddlePaddleDemo< ***@***.***>Cc:Subscribed< ***@***.***>Subject:[JunyaoHu/PaddlePaddleDemo] 数据集方便分享吗 (Issue #1) 如题,大佬数据集我想学习下,你方便分享吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
万分感谢
